$engine: 3
$onesync: on
name: ESX Legacy
author: ESX Framework
description: The official recipe of the most popular FiveM RP framework, containing Jobs, Housing, Vehicles & more!

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  
  # Download and prepare server.cfg / database
    action: download_github
    src: https://github.com/esx-framework/esx-recipes
    ref: legacy
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  # Download basic resources and ESX dependencies

  - action: connect_database

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: 
    ref: main
    dest: ./tmp/core

  - action: download_github
    src: https://github.com/esx-fork/esx_addonaccount
    ref: main
    dest: ./tmp/addons/esx_addonaccount

  - action: download_github
    src: https://github.com/esx-fork/esx_addoninventory
    ref: main
    dest: ./tmp/addons/esx_addoninventory

  - action: download_github
    src: https://github.com/esx-fork/esx_datastore
    ref: main
    dest: ./tmp/addons/esx_datastore

  - action: download_github
    src: https://github.com/esx-fork/esx_policejob
    ref: main
    dest: ./tmp/addons/esx_policejob

  - action: download_github
    src: https://github.com/esx-fork/esx_service
    ref: main
    dest: ./tmp/addons/esx_service

  - action: download_github
    src: https://github.com/esx-fork/esx_rpchat
    ref: main
    dest: ./tmp/addons/esx_rpchat

  - action: download_github
    src: https://github.com/esx-fork/esx_cruisecontrol
    ref: main
    dest: ./tmp/addons/esx_cruisecontrol

  - action: download_github
    src: https://github.com/esx-fork/esx_basicneeds
    ref: main
    dest: ./tmp/addons/esx_basicneeds

  - action: download_github
    src: https://github.com/esx-fork/esx_clotheshop
    ref: main
    dest: ./tmp/addons/esx_clotheshop

  - action: download_github
    src: https://github.com/esx-fork/esx_optionalneeds
    ref: main
    dest: ./tmp/addons/esx_optionalneeds

  - action: waste_time # prevent github throttling
    seconds: 5

  - action: download_github
    src: https://github.com/esx-fork/esx_property
    ref: main
    dest: ./tmp/addons/esx_property

  - action: download_github
    src: https://github.com/esx-fork/esx_dmvschool
    ref: main
    dest: ./tmp/addons/esx_dmvschool

  - action: download_github
    src: https://github.com/esx-fork/esx_barbershop
    ref: main
    dest: ./tmp/addons/esx_barbershop

  - action: download_github
    src: https://github.com/esx-fork/esx_weaponshop
    ref: main
    dest: ./tmp/addons/esx_weaponshop

  - action: download_github
    src: https://github.com/esx-fork/esx_shops
    ref: main
    dest: ./tmp/addons/esx_shops

  - action: download_github
    src: https://github.com/esx-fork/esx_taxijob
    ref: main
    dest: ./tmp/addons/esx_taxijob

  - action: download_github
    src: https://github.com/esx-fork/esx_billing
    ref: main
    dest: ./tmp/addons/esx_billing

  - action: download_github
    src: https://github.com/esx-fork/esx_drugs
    ref: main
    dest: ./tmp/addons/esx_drugs

  - action: download_github
    src: https://github.com/esx-fork/esx_garage
    ref: main
    dest: ./tmp/addons/esx_garage

  - action: download_github
    src: https://github.com/esx-fork/esx_vehicleshop
    ref: main
    dest: ./tmp/addons/esx_vehicleshop

  - action: download_github
    src: https://github.com/esx-fork/esx_joblisting
    ref: main
    dest: ./tmp/addons/esx_joblisting

  - action: download_github
    src: https://github.com/esx-fork/esx_banking
    ref: main
    dest: ./tmp/addons/esx_banking

  - action: download_github
    src: https://github.com/esx-fork/esx_lscustom
    ref: main
    dest: ./tmp/addons/esx_lscustom

  - action: download_github
    src: https://github.com/esx-fork/esx_society
    ref: main
    dest: ./tmp/addons/esx_society

  - action: waste_time # prevent github throttling
    seconds: 5

  - action: download_github
    src: https://github.com/esx-fork/esx_license
    ref: main
    dest: ./tmp/addons/esx_license

  - action: download_github
    src: https://github.com/esx-fork/esx_accessories
    ref: main
    dest: ./tmp/addons/esx_accessories

  - action: download_github
    src: https://github.com/esx-fork/esx_jobs
    ref: main
    dest: ./tmp/addons/esx_jobs

  - action: download_github
    src: https://github.com/esx-fork/esx_ambulancejob
    ref: main
    dest: ./tmp/addons/esx_ambulancejob

  - action: download_github
    src: https://github.com/esx-fork/esx_mechanicjob
    ref: main
    dest: ./tmp/addons/esx_mechanicjob

  - action: download_github
    src: https://github.com/esx-fork/esx_animations
    ref: main
    dest: ./tmp/addons/esx_animations

  - action: download_github
    src: https://github.com/esx-fork/esx_boat
    ref: main
    dest: ./tmp/addons/esx_boat

  - action: download_github
    src: https://github.com/esx-fork/esx_phone
    ref: main
    dest: ./tmp/addons/esx_phone

  - action: download_github
    src: https://github.com/esx-fork/esx_status
    ref: main
    dest: ./tmp/addons/esx_status
    
  - action: download_github
    src: https://github.com/esx-fork/esx_sit
    ref: main
    dest: ./tmp/addons/esx_sit

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[core]

  - action: move_path
    src: ./tmp/addons/
    dest: ./resources/[esx_addons]

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  - action: query_database
  - file: ./tmp/core/[SQL]/legacy.sql

  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/oxmysql.zip

  ## Cleanup
  - action: remove_path
    path: ./tmp
